//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  projekty: Projekty;
  projektyConnection: ProjektyConnection;
  clanky: Clanky;
  clankyConnection: ClankyConnection;
  rada: Rada;
  radaConnection: RadaConnection;
  partneri: Partneri;
  partneriConnection: PartneriConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryProjektyArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryProjektyConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ProjektyFilter>;
};


export type QueryClankyArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryClankyConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ClankyFilter>;
};


export type QueryRadaArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryRadaConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<RadaFilter>;
};


export type QueryPartneriArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPartneriConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PartneriFilter>;
};

export type DocumentFilter = {
  projekty?: InputMaybe<ProjektyFilter>;
  clanky?: InputMaybe<ClankyFilter>;
  rada?: InputMaybe<RadaFilter>;
  partneri?: InputMaybe<PartneriFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Projekty | Clanky | Rada | Partneri | Folder;

export type Projekty = Node & Document & {
  __typename?: 'Projekty';
  title: Scalars['String']['output'];
  order?: Maybe<Scalars['Float']['output']>;
  perex?: Maybe<Scalars['String']['output']>;
  cover?: Maybe<Scalars['String']['output']>;
  icon?: Maybe<Scalars['String']['output']>;
  showOnHome?: Maybe<Scalars['Boolean']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type ProjektyBodyImageWrapFilter = {
  image?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
  align?: InputMaybe<StringFilter>;
  caption?: InputMaybe<StringFilter>;
};

export type ProjektyBodyFilter = {
  imageWrap?: InputMaybe<ProjektyBodyImageWrapFilter>;
};

export type ProjektyFilter = {
  title?: InputMaybe<StringFilter>;
  order?: InputMaybe<NumberFilter>;
  perex?: InputMaybe<StringFilter>;
  cover?: InputMaybe<ImageFilter>;
  icon?: InputMaybe<StringFilter>;
  showOnHome?: InputMaybe<BooleanFilter>;
  body?: InputMaybe<ProjektyBodyFilter>;
};

export type ProjektyConnectionEdges = {
  __typename?: 'ProjektyConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Projekty>;
};

export type ProjektyConnection = Connection & {
  __typename?: 'ProjektyConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ProjektyConnectionEdges>>>;
};

export type Clanky = Node & Document & {
  __typename?: 'Clanky';
  title: Scalars['String']['output'];
  date: Scalars['String']['output'];
  category?: Maybe<Scalars['String']['output']>;
  perex?: Maybe<Scalars['String']['output']>;
  cover?: Maybe<Scalars['String']['output']>;
  source?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ClankyBodyImageWrapFilter = {
  image?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
  align?: InputMaybe<StringFilter>;
  caption?: InputMaybe<StringFilter>;
};

export type ClankyBodyFilter = {
  imageWrap?: InputMaybe<ClankyBodyImageWrapFilter>;
};

export type ClankyFilter = {
  title?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  category?: InputMaybe<StringFilter>;
  perex?: InputMaybe<StringFilter>;
  cover?: InputMaybe<ImageFilter>;
  source?: InputMaybe<StringFilter>;
  body?: InputMaybe<ClankyBodyFilter>;
};

export type ClankyConnectionEdges = {
  __typename?: 'ClankyConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Clanky>;
};

export type ClankyConnection = Connection & {
  __typename?: 'ClankyConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ClankyConnectionEdges>>>;
};

export type Rada = Node & Document & {
  __typename?: 'Rada';
  name: Scalars['String']['output'];
  role?: Maybe<Scalars['String']['output']>;
  order?: Maybe<Scalars['Float']['output']>;
  photo?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type RadaFilter = {
  name?: InputMaybe<StringFilter>;
  role?: InputMaybe<StringFilter>;
  order?: InputMaybe<NumberFilter>;
  photo?: InputMaybe<ImageFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type RadaConnectionEdges = {
  __typename?: 'RadaConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Rada>;
};

export type RadaConnection = Connection & {
  __typename?: 'RadaConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<RadaConnectionEdges>>>;
};

export type Partneri = Node & Document & {
  __typename?: 'Partneri';
  name: Scalars['String']['output'];
  order?: Maybe<Scalars['Float']['output']>;
  url?: Maybe<Scalars['String']['output']>;
  logo?: Maybe<Scalars['String']['output']>;
  featured?: Maybe<Scalars['Boolean']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PartneriFilter = {
  name?: InputMaybe<StringFilter>;
  order?: InputMaybe<NumberFilter>;
  url?: InputMaybe<StringFilter>;
  logo?: InputMaybe<ImageFilter>;
  featured?: InputMaybe<BooleanFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type PartneriConnectionEdges = {
  __typename?: 'PartneriConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Partneri>;
};

export type PartneriConnection = Connection & {
  __typename?: 'PartneriConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PartneriConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateProjekty: Projekty;
  createProjekty: Projekty;
  updateClanky: Clanky;
  createClanky: Clanky;
  updateRada: Rada;
  createRada: Rada;
  updatePartneri: Partneri;
  createPartneri: Partneri;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateProjektyArgs = {
  relativePath: Scalars['String']['input'];
  params: ProjektyMutation;
};


export type MutationCreateProjektyArgs = {
  relativePath: Scalars['String']['input'];
  params: ProjektyMutation;
};


export type MutationUpdateClankyArgs = {
  relativePath: Scalars['String']['input'];
  params: ClankyMutation;
};


export type MutationCreateClankyArgs = {
  relativePath: Scalars['String']['input'];
  params: ClankyMutation;
};


export type MutationUpdateRadaArgs = {
  relativePath: Scalars['String']['input'];
  params: RadaMutation;
};


export type MutationCreateRadaArgs = {
  relativePath: Scalars['String']['input'];
  params: RadaMutation;
};


export type MutationUpdatePartneriArgs = {
  relativePath: Scalars['String']['input'];
  params: PartneriMutation;
};


export type MutationCreatePartneriArgs = {
  relativePath: Scalars['String']['input'];
  params: PartneriMutation;
};

export type DocumentUpdateMutation = {
  projekty?: InputMaybe<ProjektyMutation>;
  clanky?: InputMaybe<ClankyMutation>;
  rada?: InputMaybe<RadaMutation>;
  partneri?: InputMaybe<PartneriMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  projekty?: InputMaybe<ProjektyMutation>;
  clanky?: InputMaybe<ClankyMutation>;
  rada?: InputMaybe<RadaMutation>;
  partneri?: InputMaybe<PartneriMutation>;
};

export type ProjektyMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
  perex?: InputMaybe<Scalars['String']['input']>;
  cover?: InputMaybe<Scalars['String']['input']>;
  icon?: InputMaybe<Scalars['String']['input']>;
  showOnHome?: InputMaybe<Scalars['Boolean']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type ClankyMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  perex?: InputMaybe<Scalars['String']['input']>;
  cover?: InputMaybe<Scalars['String']['input']>;
  source?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type RadaMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  role?: InputMaybe<Scalars['String']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
  photo?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type PartneriMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
  logo?: InputMaybe<Scalars['String']['input']>;
  featured?: InputMaybe<Scalars['Boolean']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type ProjektyPartsFragment = { __typename: 'Projekty', title: string, order?: number | null, perex?: string | null, cover?: string | null, icon?: string | null, showOnHome?: boolean | null, body?: any | null };

export type ClankyPartsFragment = { __typename: 'Clanky', title: string, date: string, category?: string | null, perex?: string | null, cover?: string | null, source?: string | null, body?: any | null };

export type RadaPartsFragment = { __typename: 'Rada', name: string, role?: string | null, order?: number | null, photo?: string | null, body?: any | null };

export type PartneriPartsFragment = { __typename: 'Partneri', name: string, order?: number | null, url?: string | null, logo?: string | null, featured?: boolean | null, body?: any | null };

export type ProjektyQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ProjektyQuery = { __typename?: 'Query', projekty: { __typename: 'Projekty', id: string, title: string, order?: number | null, perex?: string | null, cover?: string | null, icon?: string | null, showOnHome?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ProjektyConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ProjektyFilter>;
}>;


export type ProjektyConnectionQuery = { __typename?: 'Query', projektyConnection: { __typename?: 'ProjektyConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ProjektyConnectionEdges', cursor: string, node?: { __typename: 'Projekty', id: string, title: string, order?: number | null, perex?: string | null, cover?: string | null, icon?: string | null, showOnHome?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type ClankyQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ClankyQuery = { __typename?: 'Query', clanky: { __typename: 'Clanky', id: string, title: string, date: string, category?: string | null, perex?: string | null, cover?: string | null, source?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ClankyConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ClankyFilter>;
}>;


export type ClankyConnectionQuery = { __typename?: 'Query', clankyConnection: { __typename?: 'ClankyConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ClankyConnectionEdges', cursor: string, node?: { __typename: 'Clanky', id: string, title: string, date: string, category?: string | null, perex?: string | null, cover?: string | null, source?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type RadaQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type RadaQuery = { __typename?: 'Query', rada: { __typename: 'Rada', id: string, name: string, role?: string | null, order?: number | null, photo?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type RadaConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<RadaFilter>;
}>;


export type RadaConnectionQuery = { __typename?: 'Query', radaConnection: { __typename?: 'RadaConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'RadaConnectionEdges', cursor: string, node?: { __typename: 'Rada', id: string, name: string, role?: string | null, order?: number | null, photo?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type PartneriQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PartneriQuery = { __typename?: 'Query', partneri: { __typename: 'Partneri', id: string, name: string, order?: number | null, url?: string | null, logo?: string | null, featured?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type PartneriConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PartneriFilter>;
}>;


export type PartneriConnectionQuery = { __typename?: 'Query', partneriConnection: { __typename?: 'PartneriConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PartneriConnectionEdges', cursor: string, node?: { __typename: 'Partneri', id: string, name: string, order?: number | null, url?: string | null, logo?: string | null, featured?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const ProjektyPartsFragmentDoc = gql`
    fragment ProjektyParts on Projekty {
  __typename
  title
  order
  perex
  cover
  icon
  showOnHome
  body
}
    `;
export const ClankyPartsFragmentDoc = gql`
    fragment ClankyParts on Clanky {
  __typename
  title
  date
  category
  perex
  cover
  source
  body
}
    `;
export const RadaPartsFragmentDoc = gql`
    fragment RadaParts on Rada {
  __typename
  name
  role
  order
  photo
  body
}
    `;
export const PartneriPartsFragmentDoc = gql`
    fragment PartneriParts on Partneri {
  __typename
  name
  order
  url
  logo
  featured
  body
}
    `;
export const ProjektyDocument = gql`
    query projekty($relativePath: String!) {
  projekty(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ProjektyParts
  }
}
    ${ProjektyPartsFragmentDoc}`;
export const ProjektyConnectionDocument = gql`
    query projektyConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ProjektyFilter) {
  projektyConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ProjektyParts
      }
    }
  }
}
    ${ProjektyPartsFragmentDoc}`;
export const ClankyDocument = gql`
    query clanky($relativePath: String!) {
  clanky(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ClankyParts
  }
}
    ${ClankyPartsFragmentDoc}`;
export const ClankyConnectionDocument = gql`
    query clankyConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ClankyFilter) {
  clankyConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ClankyParts
      }
    }
  }
}
    ${ClankyPartsFragmentDoc}`;
export const RadaDocument = gql`
    query rada($relativePath: String!) {
  rada(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...RadaParts
  }
}
    ${RadaPartsFragmentDoc}`;
export const RadaConnectionDocument = gql`
    query radaConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: RadaFilter) {
  radaConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...RadaParts
      }
    }
  }
}
    ${RadaPartsFragmentDoc}`;
export const PartneriDocument = gql`
    query partneri($relativePath: String!) {
  partneri(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PartneriParts
  }
}
    ${PartneriPartsFragmentDoc}`;
export const PartneriConnectionDocument = gql`
    query partneriConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PartneriFilter) {
  partneriConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PartneriParts
      }
    }
  }
}
    ${PartneriPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      projekty(variables: ProjektyQueryVariables, options?: C): Promise<{data: ProjektyQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjektyQueryVariables, query: string}> {
        return requester<{data: ProjektyQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjektyQueryVariables, query: string}, ProjektyQueryVariables>(ProjektyDocument, variables, options);
      },
    projektyConnection(variables?: ProjektyConnectionQueryVariables, options?: C): Promise<{data: ProjektyConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjektyConnectionQueryVariables, query: string}> {
        return requester<{data: ProjektyConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjektyConnectionQueryVariables, query: string}, ProjektyConnectionQueryVariables>(ProjektyConnectionDocument, variables, options);
      },
    clanky(variables: ClankyQueryVariables, options?: C): Promise<{data: ClankyQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ClankyQueryVariables, query: string}> {
        return requester<{data: ClankyQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ClankyQueryVariables, query: string}, ClankyQueryVariables>(ClankyDocument, variables, options);
      },
    clankyConnection(variables?: ClankyConnectionQueryVariables, options?: C): Promise<{data: ClankyConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ClankyConnectionQueryVariables, query: string}> {
        return requester<{data: ClankyConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ClankyConnectionQueryVariables, query: string}, ClankyConnectionQueryVariables>(ClankyConnectionDocument, variables, options);
      },
    rada(variables: RadaQueryVariables, options?: C): Promise<{data: RadaQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: RadaQueryVariables, query: string}> {
        return requester<{data: RadaQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: RadaQueryVariables, query: string}, RadaQueryVariables>(RadaDocument, variables, options);
      },
    radaConnection(variables?: RadaConnectionQueryVariables, options?: C): Promise<{data: RadaConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: RadaConnectionQueryVariables, query: string}> {
        return requester<{data: RadaConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: RadaConnectionQueryVariables, query: string}, RadaConnectionQueryVariables>(RadaConnectionDocument, variables, options);
      },
    partneri(variables: PartneriQueryVariables, options?: C): Promise<{data: PartneriQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PartneriQueryVariables, query: string}> {
        return requester<{data: PartneriQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PartneriQueryVariables, query: string}, PartneriQueryVariables>(PartneriDocument, variables, options);
      },
    partneriConnection(variables?: PartneriConnectionQueryVariables, options?: C): Promise<{data: PartneriConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PartneriConnectionQueryVariables, query: string}> {
        return requester<{data: PartneriConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PartneriConnectionQueryVariables, query: string}, PartneriConnectionQueryVariables>(PartneriConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  